pad = '<pad>'
unk = '<unk>'
bos = '<bos>'
eos = '<eos>'
arc = 'arc'
rel = 'rel'
word = 'word'
chart = 'chart'
raw_tree = 'raw_tree'
valid = 'valid'
sib = 'sibling'
relatives = 'relatives'
span_head = 'span_head'

